name: GitHub App Token Test

on:
  push:
    branches:
      - main

jobs:
  generate-github-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Set the GitHub App variables (replace with actual values)
      - name: Set GitHub App Variables
        run: |
          APP_ID=1033286
          INSTALLATION_ID=56284975

      # # 2. Convert the PEM private key to PKCS8 and save it
      # - name: Set up private key
      #   run: |
      #     cat private_key.pem
      #     openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in private_key.pem -out private_key-pkcs8.pem

      # 3. Generate JWT for GitHub App Authentication
      - name: Create GitHub App Token
        id: generate_jwt
        run: |
          # Get the issued time and expiration time (max 10 minutes)
          ISSUED_AT=$(date +%s)
          EXPIRATION=$(($ISSUED_AT + 600))

          # Base64 URL encode the header and payload
          HEADER=$(echo -n '{"alg":"RS256","typ":"JWT"}' | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
          PAYLOAD=$(echo -n "{\"iat\":$ISSUED_AT,\"exp\":$EXPIRATION,\"iss\":$APP_ID}" | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')

          # Sign the JWT using the private key
          SIGNATURE=$(echo -n "$HEADER.$PAYLOAD" | openssl dgst -sha256 -sign private_key-pkcs8.pem | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')

          # Combine header, payload, and signature to form the JWT
          JWT="$HEADER.$PAYLOAD.$SIGNATURE"
          echo "Generated JWT: $JWT"

          # Export the JWT as an environment variable
          echo "JWT=$JWT" >> $GITHUB_ENV

      # 4. Use the JWT to get an installation token via curl
      - name: Get GitHub App Installation Token
        id: get_installation_token
        run: |
          TOKEN_RESPONSE=$(curl -X POST \
            -H "Authorization: Bearer ${{ env.JWT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens)

          echo "TOKEN RESP: ${TOKEN_RESPONSE}"

          INSTALLATION_TOKEN=$(echo $TOKEN_RESPONSE | jq -r .token)
          echo "Installation Token: $INSTALLATION_TOKEN"

          echo "INSTALLATION_TOKEN=$INSTALLATION_TOKEN" >> $GITHUB_ENV

      - name: Test GitHub API with App Token
        run: |
          curl -H "Authorization: Bearer ${{ env.INSTALLATION_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/test-gh-action/actions/workflows
